package logging

import (
	"github.com/signal-weave/siglog"
)

// Action  - Events that happen within the broker.
// Warning - Events that didn't execute cleanly, but aren't errors from the
//			 broker itself. Usually bad values from clients.
// Error   - Events invoked by the broker itself that did not execute cleanly.

// ----------Object Logging----------

func LogObjectAction(msg, uid string) {
	siglog.LogEntry(msg, uid, siglog.LL_INFO)
}

func LogObjectWarning(msg, uid string) {
	siglog.LogEntry(msg, uid, siglog.LL_WARN)
}

func LogObjectError(msg, uid string) {
	siglog.LogEntry(msg, uid, siglog.LL_ERROR)
}

// ----------System Logging----------

// Logged messages generated by the broker itself rather than by message objects
// traveling through the system.

func LogSystemAction(msg string) {
	siglog.LogEntry(msg, "SYSTEM", siglog.LL_INFO)
}

func LogSystemWarning(msg string) {
	siglog.LogEntry(msg, "SYSTEM", siglog.LL_WARN)
}

func LogSystemError(msg string) {
	siglog.LogEntry(msg, "SYSTEM", siglog.LL_ERROR)
}
